version: '3.8'

services:
  postgres_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - med_remind:/var/lib/postgresql/data
    ports:
      - 5437:5432

volumes:
  med_remind:
